#
# Jailhouse AArch64 support
#
# Copyright (C) 2015 Huawei Technologies Duesseldorf GmbH
# Copyright (c) Siemens AG, 2016
#
# Authors:
#  Antonios Motakis <antonios.motakis@huawei.com>
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

include $(src)/../arm-common/Kbuild

always-y := lib.a

# units initialization order as defined by linking order:
# irqchip (common-objs-y), <generic units>
lib-y := $(common-objs-y)
lib-y += entry.o setup.o control.o mmio.o paging.o caches.o traps.o
lib-y += iommu.o smmu-v3.o ti-pvu.o
lib-y += smmu.o

# Vendor specific part
ifeq ($(CONFIG_VENDOR),mediatek)

lib-y += mtk-common.o mtk-common-clk.o mtk-common-eint.o mtk-common-gpio.o

# SoC specific part
ifeq ($(CONFIG_SOC),mt8365)
lib-y += mtk-mt8365-eint.o mtk-mt8365-gpio.o
endif

ifeq ($(CONFIG_SOC),mt8370)
lib-y += mtk-mt8188-clk.o mtk-mt8370-eint.o mtk-mt8370-gpio.o
endif

ifeq ($(CONFIG_SOC),mt8390)
lib-y += mtk-mt8188-clk.o mtk-mt8390-eint.o mtk-mt8390-gpio.o
endif
endif
